# Pandas for Data Manipulation and Analysis - Part 2.2

### Credits
- Code and text by Antonio C. Briza (acbriza at gmail.com)<br>

- The outline of Lessons 6 and 7 of this workbook is mostly adapted from Chapter 5 of *Pandas for Data Analysis, 2nd Edition* by Wes McKinney.
- Other text and code come from [10 Minutes to pandas](http://pandas.pydata.org/pandas-docs/stable/10min.html), a tutorial from Panda's documentation website.  Code and text directly lifted from this source are indicated by `[TMP]`.


Last Modified: March 15, 2019<br>
[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)

# Before you begin

First, make a copy of this notebook so that you can make changes as you please. Run and edit the copy instead of this original notebook. To copy this notebook, go to `File|Save a Copy to Drive`.

If this notebook is already a copy of the original, clear all outputs in this notebook. Go to the Menu and click on `Cell| All Outputs| Clear`. Once this is done, you're ready to go.

[あ]

<a id='contents'></a>

# TABLE OF CONTENTS

[05. Basic DataFrame Operations](#lesson5)<br>
[06. Indexing, Selection and Filtering](#lesson6)<br>
[07. Missing Data](#lesson7)<br>
[08. Operations](#lesson8)<br>

## Preliminaries

First, let's import pandas and numpy and set some display options and set plots to display in the notebook.

In [1]:
import numpy as np
import pandas as pd

np.set_printoptions(precision=4)   #set 4 decimal places for outputs from numpy
pd.options.display.max_rows=15      #display 6 rows for outputs from pandas

%matplotlib inline

<a id='lesson5'></a>

# 5. Basic DataFrame operations

Let's create a DataFrame for illustrating the operations in this lesson

### Dataset: Dummy Loan Data

In [2]:
dfL = pd.DataFrame({'amount':[5.2, 1.5, 0.75, 2.1, 3.2, 1.2],
                    'interest' :[0.14, 0.08, 0.06, 0.1, 0.12, 0.08],
                    'grade': ['B', 'A', 'C', 'A', 'D', 'A']},
                  index=['loan1','loan2','loan3','loan4','loan5','loan6'])
dfL

       amount  interest grade
loan1    5.20      0.14     B
loan2    1.50      0.08     A
loan3    0.75      0.06     C
loan4    2.10      0.10     A
loan5    3.20      0.12     D
loan6    1.20      0.08     A

## 5.1 Retrieving Columns

Columns could be selected by using square brackets and specifying a column name (like the notation in a dictionary). This returns a `Series`.

In [3]:
dfL['amount']

loan1    5.20
loan2    1.50
loan3    0.75
loan4    2.10
loan5    3.20
loan6    1.20
Name: amount, dtype: float64

In [4]:
type(dfL['amount'])

pandas.core.series.Series

In [5]:
dfL['grade']

loan1    B
loan2    A
loan3    C
loan4    A
loan5    D
loan6    A
Name: grade, dtype: object

Columns could also be accessed with the `dot` notation provided that the column name is a valid python identifier

In [6]:
dfL.amount

loan1    5.20
loan2    1.50
loan3    0.75
loan4    2.10
loan5    3.20
loan6    1.20
Name: amount, dtype: float64

In [7]:
dfL.grade

loan1    B
loan2    A
loan3    C
loan4    A
loan5    D
loan6    A
Name: grade, dtype: object

## 5.2 Retrieving Rows

Rows can be retrieved via their **labels** using the  **`loc`** indexer.  This will be discussed in greater detail later in this notebook.

In [8]:
dfL.loc['loan1']

amount       5.2
interest    0.14
grade          B
Name: loan1, dtype: object

In [9]:
dfL.loc['loan4']

amount      2.1
interest    0.1
grade         A
Name: loan4, dtype: object

## 5.3 Modifying Columns with an  Assignment Expression

Columns could be modified by assignment

### Column Assignment with a scalar

All rows are assigned the scalar value

In [10]:
dfL['grade'] = 'C'
dfL

       amount  interest grade
loan1    5.20      0.14     C
loan2    1.50      0.08     C
loan3    0.75      0.06     C
loan4    2.10      0.10     C
loan5    3.20      0.12     C
loan6    1.20      0.08     C

### Column Assignment with a list

Assigning with `lists` or numpy.ndarray requires that the length (the number rows) of the DataFrame is matched

In [11]:
v = np.random.rand(6)
dfL['interest'] = v
dfL

       amount  interest grade
loan1    5.20  0.837861     C
loan2    1.50  0.070973     C
loan3    0.75  0.456866     C
loan4    2.10  0.686649     C
loan5    3.20  0.275397     C
loan6    1.20  0.335527     C

In [12]:
# This code will produce an error since the dimensions don't match
try:
    dfL['interest'] = [0.13, 0.07, 0.05, 0.09, 0.11]
except ValueError as error:
    print('Assignment error: ', error)

Assignment error:  Length of values (5) does not match length of index (6)

The list below has the matching dimensions

In [13]:
dfL['interest'] = [0.13, 0.07, 0.05, 0.09, 0.11, 0.07]
dfL

       amount  interest grade
loan1    5.20      0.13     C
loan2    1.50      0.07     C
loan3    0.75      0.05     C
loan4    2.10      0.09     C
loan5    3.20      0.11     C
loan6    1.20      0.07     C

### Column Assignment with a Series

Assignment with a Series matches the index. Any unmatched index will be **"plugged"** with `np.nan` values

In [14]:
s = pd.Series([0.15, 0.09, 0.11,  0.09],
              index=['loan1', 'loan2','loan4', 'loan6'])
dfL['interest'] = s
dfL

       amount  interest grade
loan1    5.20      0.15     C
loan2    1.50      0.09     C
loan3    0.75       NaN     C
loan4    2.10      0.11     C
loan5    3.20       NaN     C
loan6    1.20      0.09     C

## 5.4 Adding a New Column with an  Assignment Expression

An assignment expression for a **column that does not exist** adds a new column to the DataFrame.

In [15]:
dfL['purpose'] = ['House','Car','Medical','Car','House', 'Medical']
dfL

       amount  interest grade  purpose
loan1    5.20      0.15     C    House
loan2    1.50      0.09     C      Car
loan3    0.75       NaN     C  Medical
loan4    2.10      0.11     C      Car
loan5    3.20       NaN     C    House
loan6    1.20      0.09     C  Medical

## 5.5 Adding a New Row with `Concat`

A new row could be added to a DataFrame. To do this, pass a `Series` with a `name` to `pd.concat()`

In [24]:
help(pd.concat)

Help on function concat in module pandas.core.reshape.concat:

concat(
    objs: 'Iterable[Series | DataFrame] | Mapping[HashableT, Series | DataFrame]',
    *,
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys: 'Iterable[Hashable] | None' = None,
    levels=None,
    names: 'list[HashableT] | None' = None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool | None' = None
) -> 'DataFrame | Series'
    Concatenate pandas objects along a particular axis.

    Allows optional set logic along the other axes.

    Can also add a layer of hierarchical indexing on the concatenation axis,
    which may be useful if the labels are the same (or overlapping) on
    the passed axis number.

    Parameters
    ----------
    objs : a sequence or mapping of Series or DataFrame objects
        If a mapping is passed, the sorted keys will be used as the `keys`
        argument, unless it is passed, in which case the values will be
        selected (see below). Any None objects will be dropped silently unless
        they are all None in which case a ValueError will be raised.
    axis : {0/'index', 1/'columns'}, default 0
        The axis to concatenate along.
    join : {'inner', 'outer'}, default 'outer'
        How to handle indexes on other axis (or axes).
    ignore_index : bool, default False
        If True, do not use the index values along the concatenation axis. The
        resulting axis will be labeled 0, ..., n - 1. This is useful if you are
        concatenating objects where the concatenation axis does not have
        meaningful indexing information. Note the index values on the other
        axes are still respected in the join.
    keys : sequence, default None
        If multiple levels passed, should contain tuples. Construct
        hierarchical index using the passed keys as the outermost level.
    levels : list of sequences, default None
        Specific levels (unique values) to use for constructing a
        MultiIndex. Otherwise they will be inferred from the keys.
    names : list, default None
        Names for the levels in the resulting hierarchical index.
    verify_integrity : bool, default False
        Check whether the new concatenated axis contains duplicates. This can
        be very expensive relative to the actual data concatenation.
    sort : bool, default False
        Sort non-concatenation axis if it is not already aligned. One exception to
        this is when the non-concatentation axis is a DatetimeIndex and join='outer'
        and the axis is not already aligned. In that case, the non-concatenation
        axis is always sorted lexicographically.
    copy : bool, default True
        If False, do not copy data unnecessarily.

    Returns
    -------
    object, type of objs
        When concatenating all ``Series`` along the index (axis=0), a
        ``Series`` is returned. When ``objs`` contains at least one
        ``DataFrame``, a ``DataFrame`` is returned. When concatenating along
        the columns (axis=1), a ``DataFrame`` is returned.

    See Also
    --------
    DataFrame.join : Join DataFrames using indexes.
    DataFrame.merge : Merge DataFrames by indexes or columns.

    Notes
    -----
    The keys, levels, and names arguments are all optional.

    A walkthrough of how this method fits in with other tools for combining
    pandas objects can be found `here
    <https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html>`__.

    It is not recommended to build DataFrames by adding single rows in a
    for loop. Build a list of rows and make a DataFrame in a single concat.

    Examples
    --------
    Combine two ``Series``.

    >>> s1 = pd.Series(['a', 'b'])
    >>> s2 = pd.Series(['c', 'd'])
    >>> pd.concat([s1, s2])
    0    a
    1    b
    0    c
    1    d
    dtype: object

    Clear the existing index and reset it in the result
    by setting the ``ignore_index`` option to ``True``.

    >>> pd.concat([s1, s2], ignore_index=True)
    0    a
    1    b
    2    c
    3    d
    dtype: object

    Add a hierarchical index at the outermost level of
    the data with the ``keys`` option.

    >>> pd.concat([s1, s2], keys=['s1', 's2'])
    s1  0    a
        1    b
    s2  0    c
        1    d
    dtype: object

    Label the index keys you create with the ``names`` option.

    >>> pd.concat([s1, s2], keys=['s1', 's2'],
    ...           names=['Series name', 'Row ID'])
    Series name  Row ID
    s1           0         a
                 1         b
    s2           0         c
                 1         d
    dtype: object

    Combine two ``DataFrame`` objects with identical columns.

    >>> df1 = pd.DataFrame([['a', 1], ['b', 2]],
    ...                    columns=['letter', 'number'])
    >>> df1
      letter  number
    0      a       1
    1      b       2
    >>> df2 = pd.DataFrame([['c', 3], ['d', 4]],
    ...                    columns=['letter', 'number'])
    >>> df2
      letter  number
    0      c       3
    1      d       4
    >>> pd.concat([df1, df2])
      letter  number
    0      a       1
    1      b       2
    0      c       3
    1      d       4

    Combine ``DataFrame`` objects with overlapping columns
    and return everything. Columns outside the intersection will
    be filled with ``NaN`` values.

    >>> df3 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']],
    ...                    columns=['letter', 'number', 'animal'])
    >>> df3
      letter  number animal
    0      c       3    cat
    1      d       4    dog
    >>> pd.concat([df1, df3], sort=False)
      letter  number animal
    0      a       1    NaN
    1      b       2    NaN
    0      c       3    cat
    1      d       4    dog

    Combine ``DataFrame`` objects with overlapping columns
    and return only those that are shared by passing ``inner`` to
    the ``join`` keyword argument.

    >>> pd.concat([df1, df3], join="inner")
      letter  number
    0      a       1
    1      b       2
    0      c       3
    1      d       4

    Combine ``DataFrame`` objects horizontally along the x axis by
    passing in ``axis=1``.

    >>> df4 = pd.DataFrame([['bird', 'polly'], ['monkey', 'george']],
    ...                    columns=['animal', 'name'])
    >>> pd.concat([df1, df4], axis=1)
      letter  number  animal    name
    0      a       1    bird   polly
    1      b       2  monkey  george

    Prevent the result from including duplicate index values with the
    ``verify_integrity`` option.

    >>> df5 = pd.DataFrame([1], index=['a'])
    >>> df5
       0
    a  1
    >>> df6 = pd.DataFrame([2], index=['a'])
    >>> df6
       0
    a  2
    >>> pd.concat([df5, df6], verify_integrity=True)
    Traceback (most recent call last):
        ...
    ValueError: Indexes have overlapping values: ['a']

    Append a single row to the end of a ``DataFrame`` object.

    >>> df7 = pd.DataFrame({'a': 1, 'b': 2}, index=[0])
    >>> df7
        a   b
    0   1   2
    >>> new_row = pd.Series({'a': 3, 'b': 4})
    >>> new_row
    a    3
    b    4
    dtype: int64
    >>> pd.concat([df7, new_row.to_frame().T], ignore_index=True)
        a   b
    0   1   2
    1   3   4

In [17]:
new_loan = pd.Series({'amount' : 0.6,
                      'interest' : 0.12,
                      'grade' : 'B',
                      'purpose' : 'Vacation'},
                     name='loan7')

In [18]:
new_loan

amount           0.6
interest        0.12
grade              B
purpose     Vacation
Name: loan7, dtype: object

In [26]:
# Adding a row using concat
dfL = pd.concat([dfL,new_loan.to_frame().T])
dfL

      amount interest grade   purpose
loan1    5.2     0.15     C     House
loan2    1.5     0.09     C       Car
loan3   0.75      NaN     C   Medical
loan4    2.1     0.11     C       Car
loan5    3.2      NaN     C     House
loan6    1.2     0.09     C   Medical
loan7    0.6     0.12     B  Vacation

## 5.6 Deleting Rows and Columns

One or more rows could be deleted using the `DataFrame.drop()` method. The default axis is `rows` (this will drop `rows`).  Passing `axis=columns` (or `axis=1`)  will drop columns.

In [27]:
help(dfL.drop)

Help on method drop in module pandas.core.frame:

drop(
    labels: 'IndexLabel | None' = None,
    *,
    axis: 'Axis' = 0,
    index: 'IndexLabel | None' = None,
    columns: 'IndexLabel | None' = None,
    level: 'Level | None' = None,
    inplace: 'bool' = False,
    errors: 'IgnoreRaise' = 'raise'
) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Drop specified labels from rows or columns.

    Remove rows or columns by specifying label names and corresponding
    axis, or by directly specifying index or column names. When using a
    multi-index, labels on different levels can be removed by specifying
    the level. See the :ref:`user guide <advanced.shown_levels>`
    for more information about the now unused levels.

    Parameters
    ----------
    labels : single label or list-like
        Index or column labels to drop. A tuple will be used as a single
        label and not treated as a list-like.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Whether to drop labels from the index (0 or 'index') or
        columns (1 or 'columns').
    index : single label or list-like
        Alternative to specifying axis (``labels, axis=0``
        is equivalent to ``index=labels``).
    columns : single label or list-like
        Alternative to specifying axis (``labels, axis=1``
        is equivalent to ``columns=labels``).
    level : int or level name, optional
        For MultiIndex, level from which the labels will be removed.
    inplace : bool, default False
        If False, return a copy. Otherwise, do operation
        in place and return None.
    errors : {'ignore', 'raise'}, default 'raise'
        If 'ignore', suppress error and only existing labels are
        dropped.

    Returns
    -------
    DataFrame or None
        Returns DataFrame or None DataFrame with the specified
        index or column labels removed or None if inplace=True.

    Raises
    ------
    KeyError
        If any of the labels is not found in the selected axis.

    See Also
    --------
    DataFrame.loc : Label-location based indexer for selection by label.
    DataFrame.dropna : Return DataFrame with labels on given axis omitted
        where (all or any) data are missing.
    DataFrame.drop_duplicates : Return DataFrame with duplicate rows
        removed, optionally only considering certain columns.
    Series.drop : Return Series with specified index labels removed.

    Examples
    --------
    >>> df = pd.DataFrame(np.arange(12).reshape(3, 4),
    ...                   columns=['A', 'B', 'C', 'D'])
    >>> df
       A  B   C   D
    0  0  1   2   3
    1  4  5   6   7
    2  8  9  10  11

    Drop columns

    >>> df.drop(['B', 'C'], axis=1)
       A   D
    0  0   3
    1  4   7
    2  8  11

    >>> df.drop(columns=['B', 'C'])
       A   D
    0  0   3
    1  4   7
    2  8  11

    Drop a row by index

    >>> df.drop([0, 1])
       A  B   C   D
    2  8  9  10  11

    Drop columns and/or rows of MultiIndex DataFrame

    >>> midx = pd.MultiIndex(levels=[['llama', 'cow', 'falcon'],
    ...                              ['speed', 'weight', 'length']],
    ...                      codes=[[0, 0, 0, 1, 1, 1, 2, 2, 2],
    ...                             [0, 1, 2, 0, 1, 2, 0, 1, 2]])
    >>> df = pd.DataFrame(index=midx, columns=['big', 'small'],
    ...                   data=[[45, 30], [200, 100], [1.5, 1], [30, 20],
    ...                         [250, 150], [1.5, 0.8], [320, 250],
    ...                         [1, 0.8], [0.3, 0.2]])
    >>> df
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            weight  1.0     0.8
            length  0.3     0.2

    Drop a specific index combination from the MultiIndex
    DataFrame, i.e., drop the combination ``'falcon'`` and
    ``'weight'``, which deletes only the corresponding row

    >>> df.drop(index=('falcon', 'weight'))
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
            length  1.5     1.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
            length  1.5     0.8
    falcon  speed   320.0   250.0
            length  0.3     0.2

    >>> df.drop(index='cow', columns='small')
                    big
    llama   speed   45.0
            weight  200.0
            length  1.5
    falcon  speed   320.0
            weight  1.0
            length  0.3

    >>> df.drop(index='length', level=1)
                    big     small
    llama   speed   45.0    30.0
            weight  200.0   100.0
    cow     speed   30.0    20.0
            weight  250.0   150.0
    falcon  speed   320.0   250.0
            weight  1.0     0.8

### Dropping Rows

First let's copy our DataFrame

In [33]:
dfL_temp = dfL.copy()
dfL_temp

      amount interest grade   purpose
loan1    5.2     0.15     C     House
loan2    1.5     0.09     C       Car
loan3   0.75      NaN     C   Medical
loan4    2.1     0.11     C       Car
loan5    3.2      NaN     C     House
loan6    1.2     0.09     C   Medical
loan7    0.6     0.12     B  Vacation

In [34]:
dfL_temp.drop('loan6')
dfL_temp

      amount interest grade   purpose
loan1    5.2     0.15     C     House
loan2    1.5     0.09     C       Car
loan3   0.75      NaN     C   Medical
loan4    2.1     0.11     C       Car
loan5    3.2      NaN     C     House
loan6    1.2     0.09     C   Medical
loan7    0.6     0.12     B  Vacation

Q: Why is row `loan6` still there?

A: The `drop()` method returns the rows/columns that are dropped. Since we did assign it to any variable, the results were lost.

Now lets do the same, but re-assign the result to `dfL_temp`

In [35]:
dfL_temp = dfL_temp.drop('loan6')
dfL_temp

      amount interest grade   purpose
loan1    5.2     0.15     C     House
loan2    1.5     0.09     C       Car
loan3   0.75      NaN     C   Medical
loan4    2.1     0.11     C       Car
loan5    3.2      NaN     C     House
loan7    0.6     0.12     B  Vacation

Another way of doing this is by passing the parameter `inplace=True`. Let's try it by deleting `loan5`

In [36]:
dfL_temp.drop('loan5', inplace=True)
dfL_temp

      amount interest grade   purpose
loan1    5.2     0.15     C     House
loan2    1.5     0.09     C       Car
loan3   0.75      NaN     C   Medical
loan4    2.1     0.11     C       Car
loan7    0.6     0.12     B  Vacation

You can drop multiple rows by passing a list of labels

In [ ]:
dfL_temp.drop(['loan2', 'loan3'], inplace=True)
dfL_temp

### Dropping Columns

Columns could be passed by passing `axis=columns` or `axis=1` to `drop()`

In [37]:
dfL_temp2 = dfL.copy()
dfL_temp2

      amount interest grade   purpose
loan1    5.2     0.15     C     House
loan2    1.5     0.09     C       Car
loan3   0.75      NaN     C   Medical
loan4    2.1     0.11     C       Car
loan5    3.2      NaN     C     House
loan6    1.2     0.09     C   Medical
loan7    0.6     0.12     B  Vacation

In [38]:
dfL_temp2.drop(['purpose', 'grade'], axis='columns', inplace=True)
dfL_temp2

      amount interest
loan1    5.2     0.15
loan2    1.5     0.09
loan3   0.75      NaN
loan4    2.1     0.11
loan5    3.2      NaN
loan6    1.2     0.09
loan7    0.6     0.12

[TABLE OF CONTENTS](#contents)

<a id='lesson6'></a>

# 6. Indexing, Selection and Filtering

## 6.1 Reindexing, Setting, and Resetting Indices

### reindex()

In [39]:
help(dfL.reindex)

Help on method reindex in module pandas.core.frame:

reindex(
    labels=None,
    *,
    index=None,
    columns=None,
    axis: 'Axis | None' = None,
    method: 'ReindexMethod | None' = None,
    copy: 'bool | None' = None,
    level: 'Level | None' = None,
    fill_value: 'Scalar | None' = nan,
    limit: 'int | None' = None,
    tolerance=None
) -> 'DataFrame' method of pandas.core.frame.DataFrame instance
    Conform DataFrame to new index with optional filling logic.

    Places NA/NaN in locations having no value in the previous index. A new object
    is produced unless the new index is equivalent to the current one and
    ``copy=False``.

    Parameters
    ----------

    labels : array-like, optional
        New labels / index to conform the axis specified by 'axis' to.
    index : array-like, optional
        New labels for the index. Preferably an Index object to avoid
        duplicating data.
    columns : array-like, optional
        New labels for the columns. Preferably an Index object to avoid
        duplicating data.
    axis : int or str, optional
        Axis to target. Can be either the axis name ('index', 'columns')
        or number (0, 1).
    method : {None, 'backfill'/'bfill', 'pad'/'ffill', 'nearest'}
        Method to use for filling holes in reindexed DataFrame.
        Please note: this is only applicable to DataFrames/Series with a
        monotonically increasing/decreasing index.

        * None (default): don't fill gaps
        * pad / ffill: Propagate last valid observation forward to next
          valid.
        * backfill / bfill: Use next valid observation to fill gap.
        * nearest: Use nearest valid observations to fill gap.

    copy : bool, default True
        Return a new object, even if the passed indexes are the same.

        .. note::
            The `copy` keyword will change behavior in pandas 3.0.
            `Copy-on-Write
            <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
            will be enabled by default, which means that all methods with a
            `copy` keyword will use a lazy copy mechanism to defer the copy and
            ignore the `copy` keyword. The `copy` keyword will be removed in a
            future version of pandas.

            You can already get the future behavior and improvements through
            enabling copy on write ``pd.options.mode.copy_on_write = True``
    level : int or name
        Broadcast across a level, matching Index values on the
        passed MultiIndex level.
    fill_value : scalar, default np.nan
        Value to use for missing values. Defaults to NaN, but can be any
        "compatible" value.
    limit : int, default None
        Maximum number of consecutive elements to forward or backward fill.
    tolerance : optional
        Maximum distance between original and new labels for inexact
        matches. The values of the index at the matching locations most
        satisfy the equation ``abs(index[indexer] - target) <= tolerance``.

        Tolerance may be a scalar value, which applies the same tolerance
        to all values, or list-like, which applies variable tolerance per
        element. List-like includes list, tuple, array, Series, and must be
        the same size as the index and its dtype must exactly match the
        index's type.

    Returns
    -------
    DataFrame with changed index.

    See Also
    --------
    DataFrame.set_index : Set row labels.
    DataFrame.reset_index : Remove row labels or move them to new columns.
    DataFrame.reindex_like : Change to same indices as other DataFrame.

    Examples
    --------
    ``DataFrame.reindex`` supports two calling conventions

    * ``(index=index_labels, columns=column_labels, ...)``
    * ``(labels, axis={'index', 'columns'}, ...)``

    We *highly* recommend using keyword arguments to clarify your
    intent.

    Create a dataframe with some fictional data.

    >>> index = ['Firefox', 'Chrome', 'Safari', 'IE10', 'Konqueror']
    >>> df = pd.DataFrame({'http_status': [200, 200, 404, 404, 301],
    ...                   'response_time': [0.04, 0.02, 0.07, 0.08, 1.0]},
    ...                   index=index)
    >>> df
               http_status  response_time
    Firefox            200           0.04
    Chrome             200           0.02
    Safari             404           0.07
    IE10               404           0.08
    Konqueror          301           1.00

    Create a new index and reindex the dataframe. By default
    values in the new index that do not have corresponding
    records in the dataframe are assigned ``NaN``.

    >>> new_index = ['Safari', 'Iceweasel', 'Comodo Dragon', 'IE10',
    ...              'Chrome']
    >>> df.reindex(new_index)
                   http_status  response_time
    Safari               404.0           0.07
    Iceweasel              NaN            NaN
    Comodo Dragon          NaN            NaN
    IE10                 404.0           0.08
    Chrome               200.0           0.02

    We can fill in the missing values by passing a value to
    the keyword ``fill_value``. Because the index is not monotonically
    increasing or decreasing, we cannot use arguments to the keyword
    ``method`` to fill the ``NaN`` values.

    >>> df.reindex(new_index, fill_value=0)
                   http_status  response_time
    Safari                 404           0.07
    Iceweasel                0           0.00
    Comodo Dragon            0           0.00
    IE10                   404           0.08
    Chrome                 200           0.02

    >>> df.reindex(new_index, fill_value='missing')
                  http_status response_time
    Safari                404          0.07
    Iceweasel         missing       missing
    Comodo Dragon     missing       missing
    IE10                  404          0.08
    Chrome                200          0.02

    We can also reindex the columns.

    >>> df.reindex(columns=['http_status', 'user_agent'])
               http_status  user_agent
    Firefox            200         NaN
    Chrome             200         NaN
    Safari             404         NaN
    IE10               404         NaN
    Konqueror          301         NaN

    Or we can use "axis-style" keyword arguments

    >>> df.reindex(['http_status', 'user_agent'], axis="columns")
               http_status  user_agent
    Firefox            200         NaN
    Chrome             200         NaN
    Safari             404         NaN
    IE10               404         NaN
    Konqueror          301         NaN

    To further illustrate the filling functionality in
    ``reindex``, we will create a dataframe with a
    monotonically increasing index (for example, a sequence
    of dates).

    >>> date_index = pd.date_range('1/1/2010', periods=6, freq='D')
    >>> df2 = pd.DataFrame({"prices": [100, 101, np.nan, 100, 89, 88]},
    ...                    index=date_index)
    >>> df2
                prices
    2010-01-01   100.0
    2010-01-02   101.0
    2010-01-03     NaN
    2010-01-04   100.0
    2010-01-05    89.0
    2010-01-06    88.0

    Suppose we decide to expand the dataframe to cover a wider
    date range.

    >>> date_index2 = pd.date_range('12/29/2009', periods=10, freq='D')
    >>> df2.reindex(date_index2)
                prices
    2009-12-29     NaN
    2009-12-30     NaN
    2009-12-31     NaN
    2010-01-01   100.0
    2010-01-02   101.0
    2010-01-03     NaN
    2010-01-04   100.0
    2010-01-05    89.0
    2010-01-06    88.0
    2010-01-07     NaN

    The index entries that did not have a value in the original data frame
    (for example, '2009-12-29') are by default filled with ``NaN``.
    If desired, we can fill in the missing values using one of several
    options.

    For example, to back-propagate the last valid value to fill the ``NaN``
    values, pass ``bfill`` as an argument to the ``method`` keyword.

    >>> df2.reindex(date_index2, method='bfill')
                prices
    2009-12-29   100.0
    2009-12-30   100.0
    2009-12-31   100.0
    2010-01-01   100.0
    2010-01-02   101.0
    2010-01-03     NaN
    2010-01-04   100.0
    2010-01-05    89.0
    2010-01-06    88.0
    2010-01-07     NaN

    Please note that the ``NaN`` value present in the original dataframe
    (at index value 2010-01-03) will not be filled by any of the
    value propagation schemes. This is because filling while reindexing
    does not look at dataframe values, but only compares the original and
    desired indexes. If you do want to fill in the ``NaN`` values present
    in the original dataframe, use the ``fillna()`` method.

    See the :ref:`user guide <basics.reindexing>` for more.

 > Conform DataFrame to new index with optional filling logic, placing
    NA/NaN in locations having no value in the previous index. A **new object
    is produced** ...

#### Reindexing rows

Let's get a new object with rows `loan1` and `loan2` removed, then add `loan8` and `loan9`

In [41]:
obj1 = dfL.reindex(['loan3','loan4','loan5','loan6','loan7','loan8', 'loan9'])
obj1

      amount interest grade   purpose
loan3   0.75      NaN     C   Medical
loan4    2.1     0.11     C       Car
loan5    3.2      NaN     C     House
loan6    1.2     0.09     C   Medical
loan7    0.6     0.12     B  Vacation
loan8    NaN      NaN   NaN       NaN
loan9    NaN      NaN   NaN       NaN

#### Reindexing columns

Let's get a new object with `grade` column removed, then add a column for `occupation`

In [42]:
obj2 = dfL.reindex(columns=['amount','interest','purpose','occupation'])
obj2

      amount interest   purpose  occupation
loan1    5.2     0.15     House         NaN
loan2    1.5     0.09       Car         NaN
loan3   0.75      NaN   Medical         NaN
loan4    2.1     0.11       Car         NaN
loan5    3.2      NaN     House         NaN
loan6    1.2     0.09   Medical         NaN
loan7    0.6     0.12  Vacation         NaN

### set_index()

In [43]:
help(dfL.set_index)

Help on method set_index in module pandas.core.frame:

set_index(
    keys,
    *,
    drop: 'bool' = True,
    append: 'bool' = False,
    inplace: 'bool' = False,
    verify_integrity: 'bool' = False
) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Set the DataFrame index using existing columns.

    Set the DataFrame index (row labels) using one or more existing
    columns or arrays (of the correct length). The index can replace the
    existing index or expand on it.

    Parameters
    ----------
    keys : label or array-like or list of labels/arrays
        This parameter can be either a single column key, a single array of
        the same length as the calling DataFrame, or a list containing an
        arbitrary combination of column keys and arrays. Here, "array"
        encompasses :class:`Series`, :class:`Index`, ``np.ndarray``, and
        instances of :class:`~collections.abc.Iterator`.
    drop : bool, default True
        Delete columns to be used as the new index.
    append : bool, default False
        Whether to append columns to existing index.
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
    verify_integrity : bool, default False
        Check the new index for duplicates. Otherwise defer the check until
        necessary. Setting to False will improve the performance of this
        method.

    Returns
    -------
    DataFrame or None
        Changed row labels or None if ``inplace=True``.

    See Also
    --------
    DataFrame.reset_index : Opposite of set_index.
    DataFrame.reindex : Change to new indices or expand indices.
    DataFrame.reindex_like : Change to same indices as other DataFrame.

    Examples
    --------
    >>> df = pd.DataFrame({'month': [1, 4, 7, 10],
    ...                    'year': [2012, 2014, 2013, 2014],
    ...                    'sale': [55, 40, 84, 31]})
    >>> df
       month  year  sale
    0      1  2012    55
    1      4  2014    40
    2      7  2013    84
    3     10  2014    31

    Set the index to become the 'month' column:

    >>> df.set_index('month')
           year  sale
    month
    1      2012    55
    4      2014    40
    7      2013    84
    10     2014    31

    Create a MultiIndex using columns 'year' and 'month':

    >>> df.set_index(['year', 'month'])
                sale
    year  month
    2012  1     55
    2014  4     40
    2013  7     84
    2014  10    31

    Create a MultiIndex using an Index and a column:

    >>> df.set_index([pd.Index([1, 2, 3, 4]), 'year'])
             month  sale
       year
    1  2012  1      55
    2  2014  4      40
    3  2013  7      84
    4  2014  10     31

    Create a MultiIndex using two Series:

    >>> s = pd.Series([1, 2, 3, 4])
    >>> df.set_index([s, s**2])
          month  year  sale
    1 1       1  2012    55
    2 4       4  2014    40
    3 9       7  2013    84
    4 16     10  2014    31

 > Set the DataFrame index (row labels) using one or more existing columns. By default **yields a new object**.

In [44]:
dfL

      amount interest grade   purpose
loan1    5.2     0.15     C     House
loan2    1.5     0.09     C       Car
loan3   0.75      NaN     C   Medical
loan4    2.1     0.11     C       Car
loan5    3.2      NaN     C     House
loan6    1.2     0.09     C   Medical
loan7    0.6     0.12     B  Vacation

In [45]:
obj3 = dfL.set_index('purpose')
obj3

         amount interest grade
purpose
House       5.2     0.15     C
Car         1.5     0.09     C
Medical    0.75      NaN     C
Car         2.1     0.11     C
House       3.2      NaN     C
Medical     1.2     0.09     C
Vacation    0.6     0.12     B

As you can see, `pandas` allow duplicate indices.

Notice also that running the code below will not alter `dfL` (in fact it will do nothing as the return value of the set_index is not captured in a new variable)

In [46]:
dfL.set_index('purpose')
dfL

      amount interest grade   purpose
loan1    5.2     0.15     C     House
loan2    1.5     0.09     C       Car
loan3   0.75      NaN     C   Medical
loan4    2.1     0.11     C       Car
loan5    3.2      NaN     C     House
loan6    1.2     0.09     C   Medical
loan7    0.6     0.12     B  Vacation

### reset_index()

Using `reset_index()` on a DataFrame with 1-level of index adds the old index as a column, then a adds a new numeric index. It returns a new DataFrame.

In [47]:
help(dfL.reset_index)

Help on method reset_index in module pandas.core.frame:

reset_index(
    level: 'IndexLabel | None' = None,
    *,
    drop: 'bool' = False,
    inplace: 'bool' = False,
    col_level: 'Hashable' = 0,
    col_fill: 'Hashable' = '',
    allow_duplicates: 'bool | lib.NoDefault' = <no_default>,
    names: 'Hashable | Sequence[Hashable] | None' = None
) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Reset the index, or a level of it.

    Reset the index of the DataFrame, and use the default one instead.
    If the DataFrame has a MultiIndex, this method can remove one or more
    levels.

    Parameters
    ----------
    level : int, str, tuple, or list, default None
        Only remove the given levels from the index. Removes all levels by
        default.
    drop : bool, default False
        Do not try to insert index into dataframe columns. This resets
        the index to the default integer index.
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
    col_level : int or str, default 0
        If the columns have multiple levels, determines which level the
        labels are inserted into. By default it is inserted into the first
        level.
    col_fill : object, default ''
        If the columns have multiple levels, determines how the other
        levels are named. If None then the index name is repeated.
    allow_duplicates : bool, optional, default lib.no_default
        Allow duplicate column labels to be created.

        .. versionadded:: 1.5.0

    names : int, str or 1-dimensional list, default None
        Using the given string, rename the DataFrame column which contains the
        index data. If the DataFrame has a MultiIndex, this has to be a list or
        tuple with length equal to the number of levels.

        .. versionadded:: 1.5.0

    Returns
    -------
    DataFrame or None
        DataFrame with the new index or None if ``inplace=True``.

    See Also
    --------
    DataFrame.set_index : Opposite of reset_index.
    DataFrame.reindex : Change to new indices or expand indices.
    DataFrame.reindex_like : Change to same indices as other DataFrame.

    Examples
    --------
    >>> df = pd.DataFrame([('bird', 389.0),
    ...                    ('bird', 24.0),
    ...                    ('mammal', 80.5),
    ...                    ('mammal', np.nan)],
    ...                   index=['falcon', 'parrot', 'lion', 'monkey'],
    ...                   columns=('class', 'max_speed'))
    >>> df
             class  max_speed
    falcon    bird      389.0
    parrot    bird       24.0
    lion    mammal       80.5
    monkey  mammal        NaN

    When we reset the index, the old index is added as a column, and a
    new sequential index is used:

    >>> df.reset_index()
        index   class  max_speed
    0  falcon    bird      389.0
    1  parrot    bird       24.0
    2    lion  mammal       80.5
    3  monkey  mammal        NaN

    We can use the `drop` parameter to avoid the old index being added as
    a column:

    >>> df.reset_index(drop=True)
        class  max_speed
    0    bird      389.0
    1    bird       24.0
    2  mammal       80.5
    3  mammal        NaN

    You can also use `reset_index` with `MultiIndex`.

    >>> index = pd.MultiIndex.from_tuples([('bird', 'falcon'),
    ...                                    ('bird', 'parrot'),
    ...                                    ('mammal', 'lion'),
    ...                                    ('mammal', 'monkey')],
    ...                                   names=['class', 'name'])
    >>> columns = pd.MultiIndex.from_tuples([('speed', 'max'),
    ...                                      ('species', 'type')])
    >>> df = pd.DataFrame([(389.0, 'fly'),
    ...                    (24.0, 'fly'),
    ...                    (80.5, 'run'),
    ...                    (np.nan, 'jump')],
    ...                   index=index,
    ...                   columns=columns)
    >>> df
                   speed species
                     max    type
    class  name
    bird   falcon  389.0     fly
           parrot   24.0     fly
    mammal lion     80.5     run
           monkey    NaN    jump

    Using the `names` parameter, choose a name for the index column:

    >>> df.reset_index(names=['classes', 'names'])
      classes   names  speed species
                         max    type
    0    bird  falcon  389.0     fly
    1    bird  parrot   24.0     fly
    2  mammal    lion   80.5     run
    3  mammal  monkey    NaN    jump

    If the index has multiple levels, we can reset a subset of them:

    >>> df.reset_index(level='class')
             class  speed species
                      max    type
    name
    falcon    bird  389.0     fly
    parrot    bird   24.0     fly
    lion    mammal   80.5     run
    monkey  mammal    NaN    jump

    If we are not dropping the index, by default, it is placed in the top
    level. We can place it in another level:

    >>> df.reset_index(level='class', col_level=1)
                    speed species
             class    max    type
    name
    falcon    bird  389.0     fly
    parrot    bird   24.0     fly
    lion    mammal   80.5     run
    monkey  mammal    NaN    jump

    When the index is inserted under another level, we can specify under
    which one with the parameter `col_fill`:

    >>> df.reset_index(level='class', col_level=1, col_fill='species')
                  species  speed species
                    class    max    type
    name
    falcon           bird  389.0     fly
    parrot           bird   24.0     fly
    lion           mammal   80.5     run
    monkey         mammal    NaN    jump

    If we specify a nonexistent level for `col_fill`, it is created:

    >>> df.reset_index(level='class', col_level=1, col_fill='genus')
                    genus  speed species
                    class    max    type
    name
    falcon           bird  389.0     fly
    parrot           bird   24.0     fly
    lion           mammal   80.5     run
    monkey         mammal    NaN    jump

In [48]:
obj3 = dfL.reset_index()
obj3

   index amount interest grade   purpose
0  loan1    5.2     0.15     C     House
1  loan2    1.5     0.09     C       Car
2  loan3   0.75      NaN     C   Medical
3  loan4    2.1     0.11     C       Car
4  loan5    3.2      NaN     C     House
5  loan6    1.2     0.09     C   Medical
6  loan7    0.6     0.12     B  Vacation

## 6.2 Series Indexing and Slicing

Let's get a Series by getting a view of one of the columns of our loan DataFrame

In [49]:
s = dfL['amount']
s

loan1     5.2
loan2     1.5
loan3    0.75
loan4     2.1
loan5     3.2
loan6     1.2
loan7     0.6
Name: amount, dtype: object

### Indexing and Slicing with **Numeric Indices**

Indexing and Slicing a series with **numerical indices** works like NumPy array. However, to avoid ambiguity and future warnings, use `.iloc[]` for positional indexing.

In [58]:
s.iloc[0]

5.2

In [59]:
s.iloc[-1]

0.6

In [60]:
s.iloc[1:4]

loan2     1.5
loan3    0.75
loan4     2.1
Name: amount, dtype: object

Indexing using a list of integer indices

In [61]:
s.iloc[[1,3,5]]

loan2    1.5
loan4    2.1
loan6    1.2
Name: amount, dtype: object

We can also index using a boolean indexing/masking

In [65]:
s > 1.5

loan1     True
loan2    False
loan3    False
loan4     True
loan5     True
loan6    False
loan7    False
Name: amount, dtype: bool

In [64]:
#indexing using a boolean index/mask
s[s > 1.5]

loan1    5.2
loan4    2.1
loan5    3.2
Name: amount, dtype: object

#### Indexing and Slicing with **row labels**

However, for pandas Series, you could also index and slice using row labels

In [68]:
s['loan1']

5.2

In [69]:
s['loan6']

1.2

Slicing a series with row labels differs from NumPy in that **endpoints are included**

In [70]:
s['loan2':'loan5']

loan2     1.5
loan3    0.75
loan4     2.1
loan5     3.2
Name: amount, dtype: object

Indexing using a list of labels

In [71]:
s[['loan2', 'loan4', 'loan6']]

loan2    1.5
loan4    2.1
loan6    1.2
Name: amount, dtype: object

## 6.3 DataFrame Indexing

Dataframe indexing works on columns. It returns a Series or a DataFrame.

In [72]:
dfL

      amount interest grade   purpose
loan1    5.2     0.15     C     House
loan2    1.5     0.09     C       Car
loan3   0.75      NaN     C   Medical
loan4    2.1     0.11     C       Car
loan5    3.2      NaN     C     House
loan6    1.2     0.09     C   Medical
loan7    0.6     0.12     B  Vacation

In [73]:
dfL['amount']

loan1     5.2
loan2     1.5
loan3    0.75
loan4     2.1
loan5     3.2
loan6     1.2
loan7     0.6
Name: amount, dtype: object

In [74]:
dfL[['amount','interest']]

      amount interest
loan1    5.2     0.15
loan2    1.5     0.09
loan3   0.75      NaN
loan4    2.1     0.11
loan5    3.2      NaN
loan6    1.2     0.09
loan7    0.6     0.12

**You cannot select rows by indexing a DataFrame**. For this, you have to use the `loc` or `iloc` method (more on these below). Thus, the following will generate an error:

In [76]:
try:
    dfL['loan1']
except KeyError as error:
    print('Key Error indexing a DataFrame:', error)

Key Error indexing a DataFrame: 'loan1'

However, you can generate **row slices** with **numeric indexing** on DataFrames:

In [77]:
dfL[:3]

      amount interest grade  purpose
loan1    5.2     0.15     C    House
loan2    1.5     0.09     C      Car
loan3   0.75      NaN     C  Medical

In [78]:
dfL[::2]

      amount interest grade   purpose
loan1    5.2     0.15     C     House
loan3   0.75      NaN     C   Medical
loan5    3.2      NaN     C     House
loan7    0.6     0.12     B  Vacation

Rows could also be selected using boolean indexing/masking

In [79]:
mask = dfL['interest'] > .1
mask

loan1     True
loan2    False
loan3    False
loan4     True
loan5    False
loan6    False
loan7     True
Name: interest, dtype: bool

In [80]:
dfL[mask]

      amount interest grade   purpose
loan1    5.2     0.15     C     House
loan4    2.1     0.11     C       Car
loan7    0.6     0.12     B  Vacation

In [81]:
dfL[dfL['interest']>0.1]

      amount interest grade   purpose
loan1    5.2     0.15     C     House
loan4    2.1     0.11     C       Car
loan7    0.6     0.12     B  Vacation

## 6.4 Numpy-like Slicing with `loc` and `iloc`

#### Review

As a quick review, remember the following:

**Series**
- integer indexing and slicing work like NumPy arrays
- label indexing is also possible
- label slicing include the endpoints, unlike index-slicing in NumPy arrays
- slicing using a list of indices or labels
- slicing using a boolean indexing is possible

**DataFrame**
- integer indexing is **not possible**. (For this you have to use `iloc[]`)
- label indexing selects **columns**
- slicing using a list of column labels is possible
    - this selects columns
- slicing using integer slices is possible
    - this selects rows
    - this is made avaliable for convenience
    - the more general method is to use `iloc[]`
- slicing using a boolean indexing is possible
    - this selects rows

#### Introducing `loc[]` and `iloc[]` indexing operators

The `loc[]` and `iloc[]` indexing operators exist to  provide NumPy-like notation for slicing DataFrames by using row/column labels (via `loc`) or integer positions (via `iloc`).

### 6.4.1 Label Slicing with `loc[]`

In [82]:
dfL

      amount interest grade   purpose
loan1    5.2     0.15     C     House
loan2    1.5     0.09     C       Car
loan3   0.75      NaN     C   Medical
loan4    2.1     0.11     C       Car
loan5    3.2      NaN     C     House
loan6    1.2     0.09     C   Medical
loan7    0.6     0.12     B  Vacation

#### Slices of Rows

In [83]:
dfL.loc[:'loan3'] # dfL.loc[:'loan3',] or dfL.loc[:'loan3',:] will give the same output

      amount interest grade  purpose
loan1    5.2     0.15     C    House
loan2    1.5     0.09     C      Car
loan3   0.75      NaN     C  Medical

In [84]:
dfL.loc['loan2':'loan4'] #notice that the endpoint IS included

      amount interest grade  purpose
loan2    1.5     0.09     C      Car
loan3   0.75      NaN     C  Medical
loan4    2.1     0.11     C      Car

In [85]:
dfL.loc['loan1':'loan5':2] #notice that the endpoint IS included

      amount interest grade  purpose
loan1    5.2     0.15     C    House
loan3   0.75      NaN     C  Medical
loan5    3.2      NaN     C    House

In [86]:
dfL.loc[['loan1','loan5']]

      amount interest grade purpose
loan1    5.2     0.15     C   House
loan5    3.2      NaN     C   House

#### Slices of Columns

To specify column slices, the first element of the slice has to contain `:,` which selects all rows in the DataFrame.

In [87]:
dfL.loc[:, :'interest']

      amount interest
loan1    5.2     0.15
loan2    1.5     0.09
loan3   0.75      NaN
loan4    2.1     0.11
loan5    3.2      NaN
loan6    1.2     0.09
loan7    0.6     0.12

Omitting `:,` above will produce a DataFrame without rows. This is because you only provided the row slice, and since none of the row labels matches, you get an empty DataFrame.

In [88]:
dfL.loc[:'interest']

Empty DataFrame
Columns: [amount, interest, grade, purpose]
Index: []

We fix it by adding `:,`, as mentioned earlier.

In [89]:
dfL.loc[:, 'interest':]

      interest grade   purpose
loan1     0.15     C     House
loan2     0.09     C       Car
loan3      NaN     C   Medical
loan4     0.11     C       Car
loan5      NaN     C     House
loan6     0.09     C   Medical
loan7     0.12     B  Vacation

In [90]:
dfL.loc[:, ['amount', 'interest']]

      amount interest
loan1    5.2     0.15
loan2    1.5     0.09
loan3   0.75      NaN
loan4    2.1     0.11
loan5    3.2      NaN
loan6    1.2     0.09
loan7    0.6     0.12

#### "block" slices

Combining row and column slicing can help us create 'block' slices

In [91]:
dfL.loc['loan4':, :'interest']

      amount interest
loan4    2.1     0.11
loan5    3.2      NaN
loan6    1.2     0.09
loan7    0.6     0.12

In [92]:
dfL.loc[['loan1','loan3'], ['amount','interest']]

      amount interest
loan1    5.2     0.15
loan3   0.75      NaN

### 6.4.2 Positional Slicing with `iloc[]`

`iloc` works like `loc`, but for integer indices instead of labels. Keep in mind that endpoints are not included in `iloc` indexing.

In [93]:
dfL

      amount interest grade   purpose
loan1    5.2     0.15     C     House
loan2    1.5     0.09     C       Car
loan3   0.75      NaN     C   Medical
loan4    2.1     0.11     C       Car
loan5    3.2      NaN     C     House
loan6    1.2     0.09     C   Medical
loan7    0.6     0.12     B  Vacation

#### Slices of rows

In [94]:
dfL.iloc[:3] # dfL.iloc[:3,] or dfL.iloc[:3,:] will give the same output

      amount interest grade  purpose
loan1    5.2     0.15     C    House
loan2    1.5     0.09     C      Car
loan3   0.75      NaN     C  Medical

Notice that `index 3` (row label `loan4`) is not included in the slice

In [95]:
dfL.iloc[1:3] #notice that the endpoint is NOT included

      amount interest grade  purpose
loan2    1.5     0.09     C      Car
loan3   0.75      NaN     C  Medical

In [96]:
dfL.iloc[:4:2] #notice that the endpoint is NOT included

      amount interest grade  purpose
loan1    5.2     0.15     C    House
loan3   0.75      NaN     C  Medical

In [97]:
dfL.iloc[[0,4]]

      amount interest grade purpose
loan1    5.2     0.15     C   House
loan5    3.2      NaN     C   House

#### slices of columns

To specify column slices, the first element of the slice has to contain `:,` which will select all rows.

In [98]:
dfL.iloc[:, :2]

      amount interest
loan1    5.2     0.15
loan2    1.5     0.09
loan3   0.75      NaN
loan4    2.1     0.11
loan5    3.2      NaN
loan6    1.2     0.09
loan7    0.6     0.12

Omitting `:,` above will select rows. This is because you are actually providing a row slice.

In [99]:
dfL.iloc[:2]

      amount interest grade purpose
loan1    5.2     0.15     C   House
loan2    1.5     0.09     C     Car

In [100]:
dfL.iloc[:, 2:]

      grade   purpose
loan1     C     House
loan2     C       Car
loan3     C   Medical
loan4     C       Car
loan5     C     House
loan6     C   Medical
loan7     B  Vacation

In [101]:
dfL.iloc[:, [0, 1]]

      amount interest
loan1    5.2     0.15
loan2    1.5     0.09
loan3   0.75      NaN
loan4    2.1     0.11
loan5    3.2      NaN
loan6    1.2     0.09
loan7    0.6     0.12

#### "block" slices

Combining row and column slicing can help us create 'block' slices

In [102]:
dfL.iloc[3:, :2]

      amount interest
loan4    2.1     0.11
loan5    3.2      NaN
loan6    1.2     0.09
loan7    0.6     0.12

In [103]:
dfL.iloc[[0,4], [0,1]]

      amount interest
loan1    5.2     0.15
loan5    3.2      NaN

## 6.5 Selecting Single Values with `at` and `iat`

### with `at` and `iat`

While `loc` and `iloc` can be used to select single values...

In [104]:
dfL.loc['loan1', 'amount']

5.2

In [105]:
dfL.iloc[0, 0]

5.2

for faster accessing of a single value (e.g. for making production-level code), it is better to use `at` and `iat`:

In [106]:
dfL.at['loan1', 'amount']

5.2

In [ ]:
dfL.iat[0, 0]

Compare time for executing  for 10000 times

In [107]:
%%timeit -n 10000
dfL.loc['loan1', 'amount']

5.33 µs ± 154 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

In [108]:
%%timeit -n 10000
dfL.at['loan1', 'amount']

3.93 µs ± 927 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

[TABLE OF CONTENTS](#contents)

<a id='lesson7'></a>

# 7. Missing Data

Let's take a look at another dataset

In [109]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [110]:
%cd /content/drive/My\ Drive/ColabNotebooks/ICT110-AppDev/ColabNotes

/content/drive/My Drive/ColabNotebooks/ICT110-AppDev/ColabNotes

In [137]:
ls Datasets/

 Energy_Indicators.xls           Loan_Default.csv
 EnergyXLS.jpg                   temp_data.csv
 gdp_all_na_dropped.xlsx         temp_data.xlsx
'GDP(PPP)_LifeExpectancy.xlsx'   WorldBank_WHO_Country_Dataset_2015.csv
 hprice1_ex8-4.csv

In [138]:
dfG = pd.read_csv('Datasets/WorldBank_WHO_Country_Dataset_2015.csv',
                  usecols =[0,1,2,3,4],    # use column indices 1,2,3,4,5
                  names=[
                      'Country',
                      'Life_Exp',
                      'GDP',
                      'Population',
                      'Inc_Class'
                      ],                  #column names
                  na_values=['', '.'],   # invalid (N/A) values
                  header=0
)
dfG

    Country   Life_Exp           GDP  Population Inc_Class
0       ABW  75.405000  2.962907e+09      107906         H
1       AFE  61.713031  9.099053e+11   607123269       NaN
2       AFG  62.270000  1.913422e+10    33831764         L
3       AFW  56.033996  7.780375e+11   417536152       NaN
4       AGO  61.042000  1.025431e+11    28157798        LM
..      ...        ...           ...         ...       ...
256     XKX  76.024000  6.295845e+09     1788274        UM
257     YEM  66.761000  4.244449e+10    31159379         L
258     ZAF  64.053000  3.467098e+11    56723537        UM
259     ZMB  60.728000  2.125122e+10    16399089        LM
260     ZWE  58.989000  1.997325e+10    14399013        LM

[261 rows x 5 columns]

In [144]:
dfG.shape

(261, 5)

In [145]:
dfG.describe()

         Life_Exp           GDP    Population
count  261.000000  2.560000e+02  2.610000e+02
mean    71.771971  2.131059e+12  2.779660e+08
std      8.016338  7.624593e+12  9.180351e+08
min     39.757000  3.675529e+07  1.095400e+04
25%     65.909000  8.665418e+09  1.453923e+06
50%     72.932000  4.806571e+10  9.797755e+06
75%     77.451220  4.657971e+11  5.108906e+07
max     85.323000  7.583935e+13  7.441085e+09

#### Energy_Indicators.xls

In [141]:
dEG = pd.read_excel(
    'Datasets/Energy_Indicators.xls',
    skiprows=17,
    skipfooter=38,
    usecols=list(range(2, 6)),
    names=[
        'Country',
        'Energy Supply',
        'Energy Supply per Capita',
        '% Renewable'
    ],
    na_values='...')
dEG

,Country,Energy Supply,Energy Supply per Capita,% Renewable
0,Afghanistan,321.0,10.0,78.669280
1,Albania,102.0,35.0,100.000000
2,Algeria,1959.0,51.0,0.551010
3,American Samoa,NaN,NaN,0.641026
4,Andorra,9.0,121.0,88.695650
...,...,...,...,...
222,Viet Nam,2554.0,28.0,45.321520
223,Wallis and Futuna Islands,0.0,26.0,0.000000
224,Yemen,344.0,13.0,0.000000
225,Zambia,400.0,26.0,99.714670
226,Zimbabwe,480.0,32.0,52.536120

In [146]:
dEG.shape

(227, 4)

In [147]:
dEG.describe()

       Energy Supply  Energy Supply per Capita  % Renewable
count     222.000000                222.000000   227.000000
mean     2457.981982                 90.666667    28.086077
std     11039.145412                116.234887    31.903505
min         0.000000                  2.000000     0.000000
25%        33.000000                 21.250000     0.022893
50%       189.500000                 51.000000    14.814810
75%       996.250000                117.750000    50.168620
max    127191.000000                957.000000   100.000000

## 7.1 Dropping Missing Data

You can drop columns or rows using `dropna()` method

In [117]:
help(dfG.dropna)

Help on method dropna in module pandas.core.frame:

dropna(
    *,
    axis: 'Axis' = 0,
    how: 'AnyAll | lib.NoDefault' = <no_default>,
    thresh: 'int | lib.NoDefault' = <no_default>,
    subset: 'IndexLabel | None' = None,
    inplace: 'bool' = False,
    ignore_index: 'bool' = False
) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Remove missing values.

    See the :ref:`User Guide <missing_data>` for more on which values are
    considered missing, and how to work with missing data.

    Parameters
    ----------
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Determine if rows or columns which contain missing values are
        removed.

        * 0, or 'index' : Drop rows which contain missing values.
        * 1, or 'columns' : Drop columns which contain missing value.

        Only a single axis is allowed.

    how : {'any', 'all'}, default 'any'
        Determine if row or column is removed from DataFrame, when we have
        at least one NA or all NA.

        * 'any' : If any NA values are present, drop that row or column.
        * 'all' : If all values are NA, drop that row or column.

    thresh : int, optional
        Require that many non-NA values. Cannot be combined with how.
    subset : column label or sequence of labels, optional
        Labels along other axis to consider, e.g. if you are dropping rows
        these would be a list of columns to include.
    inplace : bool, default False
        Whether to modify the DataFrame rather than creating a new one.
    ignore_index : bool, default ``False``
        If ``True``, the resulting axis will be labeled 0, 1, …, n - 1.

        .. versionadded:: 2.0.0

    Returns
    -------
    DataFrame or None
        DataFrame with NA entries dropped from it or None if ``inplace=True``.

    See Also
    --------
    DataFrame.isna: Indicate missing values.
    DataFrame.notna : Indicate existing (non-missing) values.
    DataFrame.fillna : Replace missing values.
    Series.dropna : Drop missing values.
    Index.dropna : Drop missing indices.

    Examples
    --------
    >>> df = pd.DataFrame({"name": ['Alfred', 'Batman', 'Catwoman'],
    ...                    "toy": [np.nan, 'Batmobile', 'Bullwhip'],
    ...                    "born": [pd.NaT, pd.Timestamp("1940-04-25"),
    ...                             pd.NaT]})
    >>> df
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Drop the rows where at least one element is missing.

    >>> df.dropna()
         name        toy       born
    1  Batman  Batmobile 1940-04-25

    Drop the columns where at least one element is missing.

    >>> df.dropna(axis='columns')
           name
    0    Alfred
    1    Batman
    2  Catwoman

    Drop the rows where all elements are missing.

    >>> df.dropna(how='all')
           name        toy       born
    0    Alfred        NaN        NaT
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Keep only the rows with at least 2 non-NA values.

    >>> df.dropna(thresh=2)
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

    Define in which columns to look for missing values.

    >>> df.dropna(subset=['name', 'toy'])
           name        toy       born
    1    Batman  Batmobile 1940-04-25
    2  Catwoman   Bullwhip        NaT

### 7.1.1 Dropping all rows with invalid values

Let's drop all rows with invalid values and save the result in a file for manual verification.

In [148]:
df_temp = dfG.dropna()
df_temp.to_excel('Datasets/gdp_all_na_dropped.xlsx')
df_temp.describe()

         Life_Exp           GDP    Population
count  212.000000  2.120000e+02  2.120000e+02
mean    72.033189  3.551111e+11  3.485301e+07
std      8.253903  1.557175e+12  1.363125e+08
min     39.757000  3.675529e+07  1.095400e+04
25%     65.975000  6.174765e+09  8.786288e+05
50%     73.539195  2.337504e+10  6.344120e+06
75%     78.158000  1.695519e+11  2.302656e+07
max     85.323000  1.829502e+13  1.379860e+09

Notice that `count` has decreased in the  summary statistics above. We can verify this by checking the Excel file.

### 7.1.2 Dropping all rows with invalid values for a specific column

Let's drop only the rows with invalid values for the `GDP` column

In [149]:
dfG

    Country   Life_Exp           GDP  Population Inc_Class
0       ABW  75.405000  2.962907e+09      107906         H
1       AFE  61.713031  9.099053e+11   607123269       NaN
2       AFG  62.270000  1.913422e+10    33831764         L
3       AFW  56.033996  7.780375e+11   417536152       NaN
4       AGO  61.042000  1.025431e+11    28157798        LM
..      ...        ...           ...         ...       ...
256     XKX  76.024000  6.295845e+09     1788274        UM
257     YEM  66.761000  4.244449e+10    31159379         L
258     ZAF  64.053000  3.467098e+11    56723537        UM
259     ZMB  60.728000  2.125122e+10    16399089        LM
260     ZWE  58.989000  1.997325e+10    14399013        LM

[261 rows x 5 columns]

In [150]:
df_temp = dfG.dropna(subset=['GDP'])
df_temp.to_excel('gdp_na_dropped.xlsx')
df_temp.describe()

         Life_Exp           GDP    Population
count  256.000000  2.560000e+02  2.560000e+02
mean    71.698029  2.131059e+12  2.832825e+08
std      8.035365  7.624593e+12  9.261914e+08
min     39.757000  3.675529e+07  1.095400e+04
25%     65.783500  8.665418e+09  1.787820e+06
50%     72.915500  4.806571e+10  1.007863e+07
75%     77.382805  4.657971e+11  5.319661e+07
max     85.323000  7.583935e+13  7.441085e+09

### 7.1.3 Dropping after a `where` operation

In [152]:
help(dfG.where)

Help on method where in module pandas.core.generic:

where(
    cond,
    other=nan,
    *,
    inplace: 'bool_t' = False,
    axis: 'Axis | None' = None,
    level: 'Level | None' = None
) -> 'Self | None' method of pandas.core.frame.DataFrame instance
    Replace values where the condition is False.

    Parameters
    ----------
    cond : bool Series/DataFrame, array-like, or callable
        Where `cond` is True, keep the original value. Where
        False, replace with corresponding value from `other`.
        If `cond` is callable, it is computed on the Series/DataFrame and
        should return boolean Series/DataFrame or array. The callable must
        not change input Series/DataFrame (though pandas doesn't check it).
    other : scalar, Series/DataFrame, or callable
        Entries where `cond` is False are replaced with
        corresponding value from `other`.
        If other is callable, it is computed on the Series/DataFrame and
        should return scalar or Series/DataFrame. The callable must not
        change input Series/DataFrame (though pandas doesn't check it).
        If not specified, entries will be filled with the corresponding
        NULL value (``np.nan`` for numpy dtypes, ``pd.NA`` for extension
        dtypes).
    inplace : bool, default False
        Whether to perform the operation in place on the data.
    axis : int, default None
        Alignment axis if needed. For `Series` this parameter is
        unused and defaults to 0.
    level : int, default None
        Alignment level if needed.

    Returns
    -------
    Same type as caller or None if ``inplace=True``.

    See Also
    --------
    :func:`DataFrame.mask` : Return an object of same shape as
        self.

    Notes
    -----
    The where method is an application of the if-then idiom. For each
    element in the calling DataFrame, if ``cond`` is ``True`` the
    element is used; otherwise the corresponding element from the DataFrame
    ``other`` is used. If the axis of ``other`` does not align with axis of
    ``cond`` Series/DataFrame, the misaligned index positions will be filled with
    False.

    The signature for :func:`DataFrame.where` differs from
    :func:`numpy.where`. Roughly ``df1.where(m, df2)`` is equivalent to
    ``np.where(m, df1, df2)``.

    For further details and examples see the ``where`` documentation in
    :ref:`indexing <indexing.where_mask>`.

    The dtype of the object takes precedence. The fill value is casted to
    the object's dtype, if this can be done losslessly.

    Examples
    --------
    >>> s = pd.Series(range(5))
    >>> s.where(s > 0)
    0    NaN
    1    1.0
    2    2.0
    3    3.0
    4    4.0
    dtype: float64
    >>> s.mask(s > 0)
    0    0.0
    1    NaN
    2    NaN
    3    NaN
    4    NaN
    dtype: float64

    >>> s = pd.Series(range(5))
    >>> t = pd.Series([True, False])
    >>> s.where(t, 99)
    0     0
    1    99
    2    99
    3    99
    4    99
    dtype: int64
    >>> s.mask(t, 99)
    0    99
    1     1
    2    99
    3    99
    4    99
    dtype: int64

    >>> s.where(s > 1, 10)
    0    10
    1    10
    2    2
    3    3
    4    4
    dtype: int64
    >>> s.mask(s > 1, 10)
    0     0
    1     1
    2    10
    3    10
    4    10
    dtype: int64

    >>> df = pd.DataFrame(np.arange(10).reshape(-1, 2), columns=['A', 'B'])
    >>> df
       A  B
    0  0  1
    1  2  3
    2  4  5
    3  6  7
    4  8  9
    >>> m = df % 3 == 0
    >>> df.where(m, -df)
       A  B
    0  0 -1
    1 -2  3
    2 -4 -5
    3  6 -7
    4 -8  9
    >>> df.where(m, -df) == np.where(m, df, -df)
          A     B
    0  True  True
    1  True  True
    2  True  True
    3  True  True
    4  True  True
    >>> df.where(m, -df) == df.mask(~m, -df)
          A     B
    0  True  True
    1  True  True
    2  True  True
    3  True  True
    4  True  True

`DataFrames.where` allows you, by default, to set a condition such that
- rows meeting the condition are not touched
- rows not meeting the condition are set to `NaN` (vs. being dropped in Boolean Indexing)

In [153]:
dfG.where(dfG.Life_Exp > 70)

    Country  Life_Exp           GDP  Population Inc_Class
0       ABW    75.405  2.962907e+09    107906.0         H
1       NaN       NaN           NaN         NaN       NaN
2       NaN       NaN           NaN         NaN       NaN
3       NaN       NaN           NaN         NaN       NaN
4       NaN       NaN           NaN         NaN       NaN
..      ...       ...           ...         ...       ...
256     XKX    76.024  6.295845e+09   1788274.0        UM
257     NaN       NaN           NaN         NaN       NaN
258     NaN       NaN           NaN         NaN       NaN
259     NaN       NaN           NaN         NaN       NaN
260     NaN       NaN           NaN         NaN       NaN

[261 rows x 5 columns]

Combined with `dropna()`, `where()` is a useful tool that can be used for **method chaining** in reformating a DataFrame

In [154]:
dfG_high_LE = dfG.where(dfG.Life_Exp>83).dropna()
dfG_high_LE

    Country   Life_Exp           GDP   Population Inc_Class
6       AND  84.532000  2.789881e+09      72174.0         H
95      HKG  84.252683  3.093856e+11    7291300.0         H
117     JPN  83.793902  4.534439e+12  127141000.0         H
142     MAC  83.224390  4.494061e+10     642900.0         H
145     MCO  85.323000  6.264754e+09      36757.0         H
208     SMR  84.596000  1.419400e+09      32897.0         H

## 7.2 Filling Missing Data

Data could be filled with `fillna()`

In [155]:
help(dfG.fillna)

Help on method fillna in module pandas.core.generic:

fillna(
    value: 'Hashable | Mapping | Series | DataFrame | None' = None,
    *,
    method: 'FillnaOptions | None' = None,
    axis: 'Axis | None' = None,
    inplace: 'bool_t' = False,
    limit: 'int | None' = None,
    downcast: 'dict | None | lib.NoDefault' = <no_default>
) -> 'Self | None' method of pandas.core.frame.DataFrame instance
    Fill NA/NaN values using the specified method.

    Parameters
    ----------
    value : scalar, dict, Series, or DataFrame
        Value to use to fill holes (e.g. 0), alternately a
        dict/Series/DataFrame of values specifying which value to use for
        each index (for a Series) or column (for a DataFrame).  Values not
        in the dict/Series/DataFrame will not be filled. This value cannot
        be a list.
    method : {'backfill', 'bfill', 'ffill', None}, default None
        Method to use for filling holes in reindexed Series:

        * ffill: propagate last valid observation forward to next valid.
        * backfill / bfill: use next valid observation to fill gap.

        .. deprecated:: 2.1.0
            Use ffill or bfill instead.

    axis : {0 or 'index'} for Series, {0 or 'index', 1 or 'columns'} for DataFrame
        Axis along which to fill missing values. For `Series`
        this parameter is unused and defaults to 0.
    inplace : bool, default False
        If True, fill in-place. Note: this will modify any
        other views on this object (e.g., a no-copy slice for a column in a
        DataFrame).
    limit : int, default None
        If method is specified, this is the maximum number of consecutive
        NaN values to forward/backward fill. In other words, if there is
        a gap with more than this number of consecutive NaNs, it will only
        be partially filled. If method is not specified, this is the
        maximum number of entries along the entire axis where NaNs will be
        filled. Must be greater than 0 if not None.
    downcast : dict, default is None
        A dict of item->dtype of what to downcast if possible,
        or the string 'infer' which will try to downcast to an appropriate
        equal type (e.g. float64 to int64 if possible).

        .. deprecated:: 2.2.0

    Returns
    -------
    Series/DataFrame or None
        Object with missing values filled or None if ``inplace=True``.

    See Also
    --------
    ffill : Fill values by propagating the last valid observation to next valid.
    bfill : Fill values by using the next valid observation to fill the gap.
    interpolate : Fill NaN values using interpolation.
    reindex : Conform object to new index.
    asfreq : Convert TimeSeries to specified frequency.

    Examples
    --------
    >>> df = pd.DataFrame([[np.nan, 2, np.nan, 0],
    ...                    [3, 4, np.nan, 1],
    ...                    [np.nan, np.nan, np.nan, np.nan],
    ...                    [np.nan, 3, np.nan, 4]],
    ...                   columns=list("ABCD"))
    >>> df
         A    B   C    D
    0  NaN  2.0 NaN  0.0
    1  3.0  4.0 NaN  1.0
    2  NaN  NaN NaN  NaN
    3  NaN  3.0 NaN  4.0

    Replace all NaN elements with 0s.

    >>> df.fillna(0)
         A    B    C    D
    0  0.0  2.0  0.0  0.0
    1  3.0  4.0  0.0  1.0
    2  0.0  0.0  0.0  0.0
    3  0.0  3.0  0.0  4.0

    Replace all NaN elements in column 'A', 'B', 'C', and 'D', with 0, 1,
    2, and 3 respectively.

    >>> values = {"A": 0, "B": 1, "C": 2, "D": 3}
    >>> df.fillna(value=values)
         A    B    C    D
    0  0.0  2.0  2.0  0.0
    1  3.0  4.0  2.0  1.0
    2  0.0  1.0  2.0  3.0
    3  0.0  3.0  2.0  4.0

    Only replace the first NaN element.

    >>> df.fillna(value=values, limit=1)
         A    B    C    D
    0  0.0  2.0  2.0  0.0
    1  3.0  4.0  NaN  1.0
    2  NaN  1.0  NaN  3.0
    3  NaN  3.0  NaN  4.0

    When filling using a DataFrame, replacement happens along
    the same column names and same indices

    >>> df2 = pd.DataFrame(np.zeros((4, 4)), columns=list("ABCE"))
    >>> df.fillna(df2)
         A    B    C    D
    0  0.0  2.0  0.0  0.0
    1  3.0  4.0  0.0  1.0
    2  0.0  0.0  0.0  NaN
    3  0.0  3.0  0.0  4.0

    Note that column D is not affected since it is not present in df2.

#### Filling a specific column with a value

In [156]:
avg = dfG.Life_Exp.mean()
avg

np.float64(71.77197108045978)

In [157]:
df_temp = dfG.fillna(value={'Life_Exp':avg})
df_temp.to_excel('Datasets/gdp_lexp_na_filled.xlsx')
df_temp

    Country   Life_Exp           GDP  Population Inc_Class
0       ABW  75.405000  2.962907e+09      107906         H
1       AFE  61.713031  9.099053e+11   607123269       NaN
2       AFG  62.270000  1.913422e+10    33831764         L
3       AFW  56.033996  7.780375e+11   417536152       NaN
4       AGO  61.042000  1.025431e+11    28157798        LM
..      ...        ...           ...         ...       ...
256     XKX  76.024000  6.295845e+09     1788274        UM
257     YEM  66.761000  4.244449e+10    31159379         L
258     ZAF  64.053000  3.467098e+11    56723537        UM
259     ZMB  60.728000  2.125122e+10    16399089        LM
260     ZWE  58.989000  1.997325e+10    14399013        LM

[261 rows x 5 columns]

#### Forward filling

Forward filling replaces a missing value with the previous valid value.

In [161]:
dfE = pd.DataFrame({
    'Date': pd.date_range(start='2026-01-01', periods=10, freq='D'),
    'Electricity_Price': [
        10.5, np.nan, np.nan, 12.0, np.nan,
        13.5, np.nan, 14.0, np.nan, 15.5
    ]
})

dfE

        Date  Electricity_Price
0 2026-01-01               10.5
1 2026-01-02                NaN
2 2026-01-03                NaN
3 2026-01-04               12.0
4 2026-01-05                NaN
5 2026-01-06               13.5
6 2026-01-07                NaN
7 2026-01-08               14.0
8 2026-01-09                NaN
9 2026-01-10               15.5

In [166]:
df_forward = dfE

df_forward['Electricity_Price'] = (
    df_forward['Electricity_Price'].ffill()
)

df_forward

        Date  Electricity_Price
0 2026-01-01               10.5
1 2026-01-02               10.5
2 2026-01-03               10.5
3 2026-01-04               12.0
4 2026-01-05               12.0
5 2026-01-06               13.5
6 2026-01-07               13.5
7 2026-01-08               14.0
8 2026-01-09               14.0
9 2026-01-10               15.5

In [ ]:
dfE = pd.read_csv(r'datasets\elecprice_missingdata.csv')
dfE

#### Backward Fill

Backward filling replaces a missing value with the next valid value.

In [168]:
df_backward = dfE

df_backward['Electricity_Price'] = (
    df_backward['Electricity_Price'].bfill()
)

df_backward

        Date  Electricity_Price
0 2026-01-01               10.5
1 2026-01-02               10.5
2 2026-01-03               10.5
3 2026-01-04               12.0
4 2026-01-05               12.0
5 2026-01-06               13.5
6 2026-01-07               13.5
7 2026-01-08               14.0
8 2026-01-09               14.0
9 2026-01-10               15.5

In [170]:
dfE.to_csv('Datasets/electricity_missingdata.csv',index=False)

Forward filling uses the preceding observation, while backward filling uses the succeeding observation. Both methods preserve existing values, but they may be inappropriate if the carried values do not reasonably represent the missing observations.

[TABLE OF CONTENTS](#contents)

<a id='lesson8'></a>

# 8. Operations

In [173]:
dfD = pd.DataFrame({
    '  Country ': ['Philippines', 'Japan', 'South Korea', 'Thailand'],
    ' GDP ': [471.5, 4213.0, 1871.0, 526.5],
    ' Population  ': [117337000, 123104000, 51712000, 71668000],
    ' Life Expectancy ': [70.5, 84.7, 83.5, 79.7]
})

dfD

      Country     GDP   Population    Life Expectancy
0  Philippines   471.5     117337000              70.5
1        Japan  4213.0     123104000              84.7
2  South Korea  1871.0      51712000              83.5
3     Thailand   526.5      71668000              79.7

In [193]:
dfD.columns

Index(['  Country ', ' GDP ', ' Population  ', ' Life Expectancy '], dtype='object')

Notice that some column labels contain leading or trailing whitespaces.

Use `.str.strip()` to remove whitespaces from the beginning and end of each column label and replace blank spaces between words with underscores using `.str.replace()`:

In [204]:
df_strip = dfD.copy()

df_strip.columns = df_strip.columns.str.strip()

df_strip.columns = df_strip.columns.str.replace(' ', '_')

df_strip

       Country     GDP  Population  Life_Expectancy
0  Philippines   471.5   117337000             70.5
1        Japan  4213.0   123104000             84.7
2  South Korea  1871.0    51712000             83.5
3     Thailand   526.5    71668000             79.7

## 8.1 Statistical operations

Operations in general exclude missing data. `[TMP]`

Performing a descriptive statistic on `axis=rows` (the default)

In [205]:
df_strip['Life_Expectancy'].mean()

np.float64(79.6)

In [212]:
df_strip[['GDP', 'Population', 'Life_Expectancy']].mean()

GDP                    1770.5
Population         90955250.0
Life_Expectancy          79.6
dtype: float64

Let's try another function

## 8.2 DataFrame's `apply()` method

`DataFrame.apply()` applies a function along input axis of DataFrame.

In [208]:
help(dfD.apply)

Help on method apply in module pandas.core.frame:

apply(
    func: 'AggFuncType',
    axis: 'Axis' = 0,
    raw: 'bool' = False,
    result_type: "Literal['expand', 'reduce', 'broadcast'] | None" = None,
    args=(),
    by_row: "Literal[False, 'compat']" = 'compat',
    engine: "Literal['python', 'numba']" = 'python',
    engine_kwargs: 'dict[str, bool] | None' = None,
    **kwargs
) method of pandas.core.frame.DataFrame instance
    Apply a function along an axis of the DataFrame.

    Objects passed to the function are Series objects whose index is
    either the DataFrame's index (``axis=0``) or the DataFrame's columns
    (``axis=1``). By default (``result_type=None``), the final return type
    is inferred from the return type of the applied function. Otherwise,
    it depends on the `result_type` argument.

    Parameters
    ----------
    func : function
        Function to apply to each column or row.
    axis : {0 or 'index', 1 or 'columns'}, default 0
        Axis along which the function is applied:

        * 0 or 'index': apply function to each column.
        * 1 or 'columns': apply function to each row.

    raw : bool, default False
        Determines if row or column is passed as a Series or ndarray object:

        * ``False`` : passes each row or column as a Series to the
          function.
        * ``True`` : the passed function will receive ndarray objects
          instead.
          If you are just applying a NumPy reduction function this will
          achieve much better performance.

    result_type : {'expand', 'reduce', 'broadcast', None}, default None
        These only act when ``axis=1`` (columns):

        * 'expand' : list-like results will be turned into columns.
        * 'reduce' : returns a Series if possible rather than expanding
          list-like results. This is the opposite of 'expand'.
        * 'broadcast' : results will be broadcast to the original shape
          of the DataFrame, the original index and columns will be
          retained.

        The default behaviour (None) depends on the return value of the
        applied function: list-like results will be returned as a Series
        of those. However if the apply function returns a Series these
        are expanded to columns.
    args : tuple
        Positional arguments to pass to `func` in addition to the
        array/series.
    by_row : False or "compat", default "compat"
        Only has an effect when ``func`` is a listlike or dictlike of funcs
        and the func isn't a string.
        If "compat", will if possible first translate the func into pandas
        methods (e.g. ``Series().apply(np.sum)`` will be translated to
        ``Series().sum()``). If that doesn't work, will try call to apply again with
        ``by_row=True`` and if that fails, will call apply again with
        ``by_row=False`` (backward compatible).
        If False, the funcs will be passed the whole Series at once.

        .. versionadded:: 2.1.0

    engine : {'python', 'numba'}, default 'python'
        Choose between the python (default) engine or the numba engine in apply.

        The numba engine will attempt to JIT compile the passed function,
        which may result in speedups for large DataFrames.
        It also supports the following engine_kwargs :

        - nopython (compile the function in nopython mode)
        - nogil (release the GIL inside the JIT compiled function)
        - parallel (try to apply the function in parallel over the DataFrame)

          Note: Due to limitations within numba/how pandas interfaces with numba,
          you should only use this if raw=True

        Note: The numba compiler only supports a subset of
        valid Python/numpy operations.

        Please read more about the `supported python features
        <https://numba.pydata.org/numba-doc/dev/reference/pysupported.html>`_
        and `supported numpy features
        <https://numba.pydata.org/numba-doc/dev/reference/numpysupported.html>`_
        in numba to learn what you can or cannot use in the passed function.

        .. versionadded:: 2.2.0

    engine_kwargs : dict
        Pass keyword arguments to the engine.
        This is currently only used by the numba engine,
        see the documentation for the engine argument for more information.
    **kwargs
        Additional keyword arguments to pass as keywords arguments to
        `func`.

    Returns
    -------
    Series or DataFrame
        Result of applying ``func`` along the given axis of the
        DataFrame.

    See Also
    --------
    DataFrame.map: For elementwise operations.
    DataFrame.aggregate: Only perform aggregating type operations.
    DataFrame.transform: Only perform transforming type operations.

    Notes
    -----
    Functions that mutate the passed object can produce unexpected
    behavior or errors and are not supported. See :ref:`gotchas.udf-mutation`
    for more details.

    Examples
    --------
    >>> df = pd.DataFrame([[4, 9]] * 3, columns=['A', 'B'])
    >>> df
       A  B
    0  4  9
    1  4  9
    2  4  9

    Using a numpy universal function (in this case the same as
    ``np.sqrt(df)``):

    >>> df.apply(np.sqrt)
         A    B
    0  2.0  3.0
    1  2.0  3.0
    2  2.0  3.0

    Using a reducing function on either axis

    >>> df.apply(np.sum, axis=0)
    A    12
    B    27
    dtype: int64

    >>> df.apply(np.sum, axis=1)
    0    13
    1    13
    2    13
    dtype: int64

    Returning a list-like will result in a Series

    >>> df.apply(lambda x: [1, 2], axis=1)
    0    [1, 2]
    1    [1, 2]
    2    [1, 2]
    dtype: object

    Passing ``result_type='expand'`` will expand list-like results
    to columns of a Dataframe

    >>> df.apply(lambda x: [1, 2], axis=1, result_type='expand')
       0  1
    0  1  2
    1  1  2
    2  1  2

    Returning a Series inside the function is similar to passing
    ``result_type='expand'``. The resulting column names
    will be the Series index.

    >>> df.apply(lambda x: pd.Series([1, 2], index=['foo', 'bar']), axis=1)
       foo  bar
    0    1    2
    1    1    2
    2    1    2

    Passing ``result_type='broadcast'`` will ensure the same shape
    result, whether list-like or scalar is returned by the function,
    and broadcast it along the axis. The resulting column names will
    be the originals.

    >>> df.apply(lambda x: [1, 2], axis=1, result_type='broadcast')
       A  B
    0  1  2
    1  1  2
    2  1  2

### 8.2.1 DataFrame.apply with `axis=rows`

The default index of `DataFrame.apply` (as with most/all DataFrame methods) is `rows`. Thus, using `apply` without parameters will operate down rows, or inter-rows (effectively, you're geting outputs for the columns)

In [213]:
df_strip.apply(np.sum)

Country            PhilippinesJapanSouth KoreaThailand
GDP                                             7082.0
Population                                   363821000
Life_Expectancy                                  318.4
dtype: object

Of course, we can explictly specify the axis (All these 3 parameter settings will yield the same result: `axis=rows` or `axis=0` or `axis=index`).

### 8.2.2 Using apply with a custom function

`DataFrame.apply` becomes interesting when used with a custom function

Say we want to get the range (highest minus lowest values) of our columns. We could do this with the following:

[TABLE OF CONTENTS](#contents)

# Final Words

Congratulations for reaching this far.

For advanced lessons on `pandas`, the following book is highly suggested: *Pandas for Data Analysis, 2nd Edition *by Wes McKinney

<a id='lesson10'></a>